#!/usr/bin/env node
import fs from 'fs';

const password = process.argv[2];
if (!password || password.length < 12) {
  console.error('Usage: node src/admin/setup.js <strong-password-12+-chars>');
  process.exit(1);
}

// Must match simpleHash() in src/admin/index.html
function simpleHash(str) {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash;
  }
  return hash.toString(16);
}

const hash = simpleHash(password);
const totp = crypto.randomBytes(20).toString('base64');
const config = `// Security config - generated by setup.js, DO NOT COMMIT
const ADMIN_PASSWORD_HASH = '${hash}';
const TOTP_SECRET = '${totp}';
`;

fs.writeFileSync('./src/admin/config.js', config);
console.log('Config created at src/admin/config.js (gitignored).');
console.log('Save the TOTP secret in your authenticator app now - it will not be shown again.');
console.log('\nTo use:');
console.log('1. npm run admin');
console.log('2. Open http://localhost:3001');
